//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("uNhAddIns")]
[assembly: AssemblyCopyright("Copyright (c) uNhAddIns, 2008. All rights reserved.")]
[assembly: AssemblyProduct("uNhAddIns.Adapters.CommonTests")]
[assembly: AssemblyTitle("uNhAddIns.Adapters.CommonTests")]
[assembly: CLSCompliant(true)]
[assembly: AssemblyInformationalVersion("3.0.0.774")]
[assembly: AssemblyVersion("3.0.0.774")]


